server:
  port: 80
spring:
  application:
    name: cloud-feign-order-service
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      #      defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#打开feign日志功能
logging:
  level:
    #feign日志以什么级别监控那个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug


